### PR TITLE
Add EVM+ink! Contracts Pallets to Asset Hub for Polkadot

### PR DESCRIPTION
**Pull request by sourabhniyogi**
This RFC proposes to add the two dominant smart contract programming languages in the Polkadot ecosystem to AssetHub: EVM + ink!/Coreplay.  The objective is to increase DOT Revenue by making AssetHub accessible to 
(1) Polkadot Rollups
(2) EVM smart contract programmers
(3) Coreplay smart contract programmers  
These changes in AssetHub are enabled  by key Polkadot 2.0 technologies: PolkaVM supporting Coreplay, hyper data availability in Blobs Chain.

### CODE REVIEW

**Comment by albertov19** [comment]
What is the point of this?

The whole point of Polkadot was that Parachains would provide specific functions to the broader ecosystem. By adding SmartContract capabilities to AssetHub you will use AssetHub's blockspace for something it was not meant to do.

**Comment by sourabhniyogi** [comment]
Utilizing Polkadot DA, Polkadot Rollups can bring DOT demand far greater
than Moonbeam + Astar's demand for DOT alone.

In RFC #32, it was decided that Smart Contracts could not be on the Relay
Chain.     If there is a charter enumerating all the things that AssetHub
was meant to do vs not meant to in the 2.0 era, take a look at that.

System chains are the next logical choice beyond the relay chain itself.
Out of all system chains, AssetHub is the only sensible choice.

In the 2.0 era, Polkadot Rollups should not depend on other parachains'
ability to secure CoreTime.  Depending on AssetHub is superior because it
has no risk of suddenly being unable to secure funds to acquire CoreTime
due to market conditions.

AssetHub's blockspace is hardly used at present, but enabling
AssetConversion+Polkadot Rollups (with Blobs/Sugondat) will change in the
2.0 era.

There will be many uses for AssetHub, from minting NFT collections to being
the place where stablecoins USDC + USDT are integrated with CEX.

Supporting Rollups and combining with Polkadot's superior DA (from Blobs
chains, superior relative to Ethereum) is one powerful way to bring in new
DOT to the Polkadot ecosystem.

**Comment by sourabhniyogi** [comment]
> Asset-Hub's blockspace was designed for Asset-specific things, not smart contract execution.

It was originally, but the content of this RFC argues for a change in its design to extend from "Asset-specific things" to include smart contract execution.  This supports both EVM sync patterns with those "Asset-specific things" and Polkadot 2.0 technologies:
* ink! => Coreplay
* DA for Polkadot 
Many Polkadot Rollups require EVM (deposits, withdrawals, fraud proofs, ...) -- converting them to pallets makes little engineering sense.

Many popular defi primitives can usefully work with the top assets of AssetHub (DOT, USDC, USDT), yes, without any other parachains.  This has the potential for making AssetHub accessible for everyday users and developers while bringing in additional DOT revenue from those same users and developers.  

The choice is clear:
 (1) Do not Add EVM + ink! Contracts Pallets to AssetHub,  sacrificing DOT revenue from EVM/ink!/Coreplay + Polkadot Rollups in favor of CoreTime DOT Revenue from 1.0 era Parachains.   This ARTIFICIALLY forces Polkadot developers into async patterns, leading to poor developer experiences.
 (2) Add EVM + ink! Contracts Pallets to AssetHub,  sacrificing DOT revenue from 1.0 era Parachains in favor of DOT revenue from EVM/ink!/Coreplay + Polkadot Rollups.  This gives FREEDOM for Polkadot developers to pursue hybrid sync+async patterns, leading to ideal developer experiences for both old 1.0 tech (EVM, ink!) and new 2.0 tech (Blobs/Sugondat, Coreplay)

**Comment by burdges** [comment]
AssetHub should probably move the oposite direction, meaning improve performance by optimizing for limited functionality.

As an example, you cannot safely run a smart contract chain over storage wich lacks non-membership proofs, but if you give up non-membership proofs then you could've optimal uniform depth storage.  AssetHub might or might not need non-membership proofs.  It's also possible "best effort" uniform depth storage like Cosmos works well enough in practice.  We donno right now.. 

As for strategy & revenue.. 

In elastic scaling, we'll permit parachains to make blocks faster than the relay chain, but as their speed increases their data model must address liveness concerns.  There are diverse somewhat incompatible ways smart contract chains could handle this smart contract vs liveness conflict, including networking restrictions, collator negotiations, runtime rust-like borrowing, restricted langauges, etc.

In polkadot, we've beaten ETH roll ups on the performacne vs security trade off, but we've never solved this smart contract vs liveness conflict.  And nobody else did either because the design space looks huge.

We'll likely want multiple strong smart contract chains like Moonbeam and Astar, who make different choices and explore different parts of this design space.  It's thus best if we do not step on the toes of our smart contract parachains right now.

**Comment by sourabhniyogi** [comment]
> AssetHub should probably move the oposite direction, meaning improve performance by optimizing for limited functionality.
@burdges Ser, what *performance* do you need to see improve?    Forcing Polkadot developers into asynchronous patterns to use AssetHub is unnecessary and inhibits usage of AssetHub and Polkadot generally.  The USDC and USDT assets on AssetHub are barely used, the AssetHub blockspace is barely used.  It was one thing to make the performance argument on the relay chain in RFC #32, but we're not talking about the relay chain anymore.   Having sync programming constructs on AssetHub is necessary for Polkadot Rollups, Coreplay, and to use the top 2 assets other than DOT in the ecosystem.  Failing to do this limits Polkadot growth.

> As for strategy & revenue..
> In polkadot, we've beaten ETH roll ups on the performacne vs security trade off, but we've never solved this smart contract vs liveness conflict. And nobody else did either because the design space looks huge.
It is wonderful that there is a smart contract vs liveness conflict design space problem for you + others to solve with a huge design space.  However, this RFC is not about that design space problem.  It is about adding pallets to AssetHub.  

> We'll likely want multiple strong smart contract chains like Moonbeam and Astar, who make different choices and explore different parts of this design space. It's thus best if we do not step on the toes of our smart contract parachains right now.

Your approach appears to be rooted in fear and highly regressive.  Polkadot already has these strong contract chains like Moonbeam and Astar, which will continue to exist because they are usable and successful in their own right, and have been since the end of 2021.  Two years have passed.  Now they will bring in a certain amount of CoreTime revenue in 2024 and we need to grow Polkadot to new heights.   This RFC is concerned about making AssetHub usable for defi/nfts, ink => Coreplay, and Polkadot rollups through relatively small changes that are extremely easy to justify as bringing in new DOT revenue.

**Comment by muddlebee** [comment]
What if I want to build directly on top of Polkadot/Kusama skipping the parachains and pay txn fees directly using DOT/KSM rather than parachain native token? Is Asset Hub the better viable option?

Recently I came across https://yerba.network/ by sasha(ink dev), sounds interesting to be able to pay txn fees using KSM.

**Comment by xlc** [comment]
> pay txn fees directly using DOT/KSM rather than parachain native token
You can do that on Karura / Acala from like a year ago

I do want to point it out, from a purely technical perspective, Frontier is not a good EVM stack that play nicely with the core time model or works with light client.

There are many incompatibilities between EVM and core time model, and I cannot support this unless a feasibility study is implemented.

I can list a few incompatibilities to get you start thinking:

- Account type - ss58 vs 20 bytes hex
- ED
- RPC and extra db requirement for tx data indexing

**Comment by muddlebee** [comment]
@xlc thank you for your answer, appreciate the reply. What if I want to create and use smart contracts with ink! on Polkadot directly, instead of on its parachains, because I feel it's safer and more trustworthy? Is this a possibility in near future?

I understand there are some challenges associated with it as Jeff pointed out earlier. But as a dev POV I want ink Smart Contracts as a first step into Polkadot or Kusama then scale later on into parachains if needed. 

image
[source](https://use.ink/how-it-works#use-case-3-smart-contracts-as-a-first-step-into-polkadot-or-kusama)

**Comment by xlc** [comment]
We will never have smart contracts on relaychain directly.

We may have smart contracts on a system chain. 

But what is the problem you trying to solve again?

**Comment by sourabhniyogi** [comment]
> I do want to point it out, from a purely technical perspective, Frontier is not a good EVM stack that play nicely with the core time model or works with light client.
> There are many incompatibilities between EVM and core time model, and I cannot support this unless a feasibility study is implemented.

The incompatibilities between EVM and the CoreTime model are not relevant to the RFC:
* AssetHub does NOT need CoreTime as it is a _system chain_.  As such AssetHub can add the Frontier EVM pallets with ZERO concern for CoreTime.  
* A Polkadot Rollup using EVM tech (e.g. OP Stack) also does NOT need Frontier, nor does it need to buy CoreTime -- it needs to pay for DA. 

You must have something else in mind.  Can you explain how the incompatibilities between EVM and CoreTime affect the ability to add EVM pallets to AssetHub?

[Aside: I think it would be wonderful to have a CoreEVM update that addresses the CoreTime incompatibilities so that a parachain could use EVM pallets as well]

> Account type - ss58 vs 20 bytes hex
> ED
> RPC and extra db requirement for tx data indexing
The RFC recommends that Astar follow Astar's design choices, which is the #1 parachain in the ecosystem by marketcap. 

Astar uses Frontier with a small but important set of modifications, which are well documented, easy to apply, and hardly require a "feasibility study".  There are 2 years of Astar data to act as a "feasibility study" for AssetHub to basically mirror the same judgements.

**Comment by xlc** [comment]
With ED, it is not possible to have 100% EVM compatibility. Acala have ED and not 100% EVM compatibility. Moonbeam don’t and have it. 

With Frontier, user will not be able to access EVM via light client. The EVM RPC doesn’t work with tools like Chopsticks. 

They are just unsolved problems and everyone is making some trade offs. A study is absolutely required to understand the trade offs and then allow everyone to make a decision.

**Comment by sourabhniyogi** [comment]
> With ED, it is not possible to have 100% EVM compatibility. Acala have ED and not 100% EVM compatibility. Moonbeam don’t and have it.
> 
> With Frontier, user will not be able to access EVM via light client. The EVM RPC doesn’t work with tools like Chopsticks.
> 
> They are just unsolved problems and everyone is making some trade offs. A study is absolutely required to understand the trade offs and then allow everyone to make a decision.
I think its wonderful to characterize the decisions for AssetHub in terms of tradeoffs that the Fellows and hopefully (somehow) OpenGov can understand and vote on (somehow).

Since none of your above points are about _CoreTime_ (still don't understand why you brought it up..), the tradeoff decisions concerning EVM + ink! are then about what specific choice **AssetHub** should make, which are extremely well informed by over two years from Polkadot's top 3 parachains [circa December 2021].   For the 2 parameters you brought up
 1. lower the ED further, from 0.01 DOT to 0.   This would risks state bloat (cf Moonbeam-XEN) and 0.01 DOT is $0.07.     I think this is a non-starter.
 2. adding light client support to Frontier.   Someone can try to develop this, but not having light client support for Frontier will not affect the ability to add ink!/EVM pallets to AssetHub.  

Concerning (1) and non-zero ED, is there some write up from Acala + Astar about how the non-zero ED choices _differ_ that everyone can study to decision how AssetHub should make similar or different choices?  I did not see much to go on here concerning design choices:    
 https://wiki.acala.network/integrate/acala/protocol-info#existential-deposit
 https://wiki.acala.network/get-started/acala-network/acala-account 
 https://docs.astar.network/docs/learn/interoperability/xcm/building-with-xcm/send-xc20-evm/
Did Acala do a design tradeoff doc for its ED choices and EVM+ generally?  If so, please share a link to it, we could learn from it!

Concerning (2), I am unfamiliar why requiring light support for Frontier should derail ink!/EVM support.  Can you explain this in detail?

It is NOT essential to have 100.0% EVM Compatibility, but it IS essential to support the following use cases:
 1. *Top defi*: Uniswap v2/v3/v4, Curve, etc. for AssetHub's top 3 Assets: USDC, USDT, DOT.   
 2. *Polkadot Rollups* for common Rollup platforms (OP STACK, Arbitrum Orbit, Polygon CDK)
Both of the above have been tested on Moonbeam and Astar, so there is no _technical_ blocker.  

@xlc Can you itemize what parameters you would like to see characterized in a tradeoff study?

I think its really important to recognize which parameters are truly important and use the learnings from Astar+Acala to make the correct decisions for AssetHub.

**Comment by xlc** [comment]
We have this https://evmdocs.acala.network/general/about-acala-evm+ which may or may not answer all your questions but it explains some of the design process of Acala EVM+.

For the rest of the discussion, I would like to get back to step zero. I believe the goal for all of us is to solve some issues, which you have listed a few. But I don't think you want to add smart contracts to AH for the sake of adding it. We should explore all alternatives before deciding if a particular solution (i.e. the one you proposed) is the best one.

So please define the problem.

You have listed two items:

1. Top defi: Uniswap v2/v3/v4, Curve, etc. for AssetHub's top 3 Assets: USDC, USDT, DOT.
2. Polkadot Rollups for common Rollup platforms (OP STACK, Arbitrum Orbit, Polygon CDK)

For 1: Because you did not define exactly the requirements, so my solution to the problem that you have defined is simply use one of the existing EVM parachain. I know this answer does not satisfy you but let's iterate it from here. You could say my solution does not solve some specific use case and then we could try to change this alternative approach in such way to address the use case you proposed. It could totally be implementing smart contract in AH, but should not skip the intermediary steps or I am sure our maths teacher won't be happy.

For 2: There are lot more alternatives:
- Use existing EVM chain
- Build rollup pallet and
  - deploy to an existing chain
  - deploy to a new chain

**Comment by sourabhniyogi** [comment]
> We have this https://evmdocs.acala.network/general/about-acala-evm+ which may or may not answer all your questions but it explains some of the design process of Acala EVM+.

Cool, are all the parameters you would expect from feasibility study covered in Acala's detailed overview there?     If not, what is missing?
 
> For the rest of the discussion, I would like to get back to step zero. I believe the goal for all of us is to solve some issues, which you have listed a few. But I don't think you want to add smart contracts to AH for the sake of adding it. We should explore all alternatives before deciding if a particular solution (i.e. the one you proposed) is the best one.
> 
> So please define the problem.

https://github.com/polkadot-fellows/RFCs/pull/66/files#diff-43154a8feb555fdcfd4b6110bb9cb86172abc13ac3d5030629f54e37b0976d35R37-R89

summarizes the problem of (1)+(2) below.  If you have questions in the RFC, please ask and I will clarify.  Super happy to improve the motivation section, thank you!

> You have listed two items:
> 
> 1. Top defi: Uniswap v2/v3/v4, Curve, etc. for AssetHub's top 3 Assets: USDC, USDT, DOT.
> 2. Polkadot Rollups for common Rollup platforms (OP STACK, Arbitrum Orbit, Polygon CDK)
> 
> For 1: Because you did not define exactly the requirements, so my solution to the problem that you have defined is simply use one of the existing EVM parachain. I know this answer does not satisfy you but let's iterate it from here. You could say my solution does not solve some specific use case and then we could try to change this alternative approach in such way to address the use case you proposed. It could totally be implementing smart contract in AH, but should not skip the intermediary steps or I am sure our maths teacher won't be happy.

Again, the "Motivation" section of the RFC covers this topic.   I did try to make it readable for both our math teacher and you =)   Could you kindly review that?    

> For 2: There are lot more alternatives:
> 
> * Use existing EVM chain
To summarize the content of the RFC again:
(a) FORCING async patterns onto developers and users for defi/nft applications is completely unnecessary in AssetHub.  
(b) Polkadot Rollups would trust a system chain over a parachain.  A parachain could just disappear.   And at the end of the day, we're here to improve the business of Polkadot, not the parachain.  [I understand you might see differently.]

So, this alternative should be ruled out.  Do you see differently?  

> * Build rollup pallet and
>   
>   * deploy to an existing chain
>   * deploy to a new chain

[Blobs](https://github.com/thrumdev/blobs) has the basics to serve Polkadot Rollups for a DA perspective, but converting all Rollup tech (OP, ARB, PolygonCDK) into rollup pallets is way too engineering intensive -- Thrum's shims model is just clearly better since it spares tons of engineering replication with little to gain.   In contrast, adding EVM pallets to AssetHub is largely about making tradeoff decisions based on the history of successful EVM parachains -- I do agree reviewing the tradeoffs for AssetHub adding EVM+ink/Coreplay merits careful review of the EVM+ink/Coreplay parachains.

**Comment by sourabhniyogi** [comment]
@joepetrowski (all) Is a separate "OpenEVM" SYSTEM chain (with the assetConversion pallet) -- approved by OpenGov Root Referendum -- a better way to address the need for Polkadot Rollups needing EVM?

https://twitter.com/giottodf/status/1757275333143707849

This keeps AssetHub purely doing ONE THING (yay!) and relegates the OpenEVM SYSTEM chain to do other things:
* EVM (with DOT Revenues)
* ED 0 (having the same issues as Moonbeam, aka "not scalable")
* Polkadot Rollups with Blobs Chains

The underlying thesis is that DOT Revenues from OpenEVM SYSTEM chains would exceed that of the EVM Smart Contract parachains (Moonbeam + Astar).  

Questions:
* Is it possible to have 3x or 6x the number of cores assigned to an OpenEVM SYSTEM chain to enable 2s or 1s block times?  
* What would have to happen to enable this possibility?

**Comment by joepetrowski** [comment]
> Is a separate "OpenEVM" SYSTEM chain (with the assetConversion pallet) -- approved by OpenGov Root Referendum -- a better way to address the need for Polkadot Rollups needing EVM?

Probably, yes. I'm discussing with some other Fellows the best way to essentially override the Fellowship RFC process in a way that doesn't take the single-proposal Root track, see https://github.com/polkadot-fellows/runtimes/pull/184

> Is it possible to have 3x or 6x the number of cores assigned to an OpenEVM SYSTEM chain to enable 2s or 1s block times?

Yes but that's a separate issue to "should the chain exist". It's purely a scheduling/core assignment problem, which really should be automated to scale with more load.

> If an OpenEVM chain is approved by Root Referendum to be a SYSTEM chain, what body governs changes to this system chain? Does it go through OpenGov processes or RFC processes?

IMO this would be the Fellowship. The Fellowship has a mandate to maintain and develop the Polkadot protocol. Of course, people in the Fellowship have opinions about what should be (or not be) in the protocol, but a Root referendum that says unequivocally, "the network wants X feature", should be sufficient. The Fellowship works for the network. Of course, if what the network wants is wildly insecure or reckless, the Fellowship's job would be to try to stop it or at least not support it, and at the point it would come to someone else implementing the change and doing a non-Fellowship-endorsed release/upgrade.

> Is a OpenEVM Collective a suitable choice for an alternative to both OpenGov or RFC?

I think that a new collective for this purpose is a terrible idea. We don't have a "Bridge Hub collective". Don't get me wrong, I love collectives and think they are hugely underutilized, but let's not make every single problem a nail and collectives a hammer. We already have a collective for the maintenance of the system, the Tech Fellowship, and I don't see why we'd need another Fellowship for _the maintenance of a piece of the system_.

> Another argument for EVM addition to AssetHub is to add better USDC support via Circle's CCTP contracts. Would this be better done under an OpenEVM system chain instead?

I would much rather see a solution that does not put EVM on Asset Hub.

**Comment by burdges** [comment]
> Is a separate "OpenEVM" SYSTEM chain (with the assetConversion pallet) -- approved by OpenGov Root Referendum --

Who'd maintain this?

We've multiple external parachain projects who do this job now, so does one want them to merge?  Or does someone want tresury funds to compete with them?

We do have folks doing EVM compiler work at Parity, presumably EVM->PolkaVM eventually.  We should not bring the actual EVM chain work in-house at Parity or W3F of course.

> a better way to address the need for Polkadot Rollups needing EVM?

You said "rollup" and "need" in the same sentence.  Afaik all roll ups are pessimisations vs parachains in one of two senses, either zk roll ups need exterme CPU time costs, or else optimistic roll ups need long unlocking period, meaning rollups needs days or weaks of delay when sending messages.  And optimistic roll ups have the same problem as nested relay chains that polkadot cannot validate parachain's off-chain concensus.

If someone wants a high-speed low-security chain, then we could do that in other ways, like cores with fewer approval checkers, but it still complicates messaging, which makes doing it messy.  

In brief, we already have better tech for doing what rollups do, which makes them mostly pointless.  

We can have parachains which also act like an optimistic roll up on another chain like ETH, but likely bridges superceed these.  A fully EVM programable bridge maybe interests folks.  A system EVM chain cannot facilitate these features.

**Comment by joepetrowski** [comment]
> Who'd maintain this?
> We've multiple external parachain projects who do this job now, so does one want them to merge? Or does someone want tresury funds to compete with them?
> We do have folks doing EVM compiler work at Parity, presumably EVM->PolkaVM eventually. We should not bring the actual EVM chain work in-house at Parity or W3F of course.

Like Rob said [here](https://github.com/polkadot-fellows/RFCs/pull/2#discussion_r1258024271), an RFC just says the "what". With sub-treasuries functioning now, it would make sense for people to apply for funding to implement approved RFCs.

Staying neutral to the EVM thing here, just saying that if the Root origin says "we want something", I'm sure there will be a way to make implementation happen.

**Comment by sourabhniyogi** [comment]
> Who'd maintain this?
An OpenEVM Collective, seeded with technically people deeply involved in improving Polkadot EVM technology  
 https://github.com/polkadot-evm/seeding

> We've multiple external parachain projects who do this job now, so does one want them to merge? 
Interesting question, but... they already issued their own non-DOT token in all cases I know of, that would be insane because the idea is to bring far more DOT revenue instead.

> Or does someone want tresury funds to compete with them?  
The idea is to bring far more DOT revenue with (initially or permanently) treasury-funded CoreTime cores to demonstrate that Polkadot EVM tech is not just better in theory but in the marketplace, to COMPETE not with other parachains but with Arbitrum, Optimism, Avalanche at the very least.   The "them" framing has to be not rooted in a Polkadot frame but in the broader Web3 ecosystem.

A serious % of all available cores (say, 8-16%, like 24 cores or 48 cores out of 300) can be allocated to 1-3 "OpenEVM" chains.  

If Moonbeam/Astar is using 1 "core" and operating at 6s, my naive idea is that:
 2 cores on an OpenEVM chain would operate at 3s block production times
 3 cores on an OpenEVM chain would operate at 2s (like Optimism)
 6 cores on an OpenEVM chain would operate at 1s
12 cores on an OpenEVM chain would operate at 0.5s
24 cores on an OpenEVM chain would operate at 0.25s (like Arbitrum, approximately)
This block production time trick is widely used, and everyone who knows anything about optimistic rollups also knows THAT users pretty much forget about the 7 day window etc.   A bunch of OpenEVM chains (plural, because we should retrofit XCM to this somehow). 


> In brief, we already have better tech for doing what rollups do, which makes them mostly pointless.
Your conclusion is that Polkadot Optimisic Rollups with a "Blobs" chain and Optimism and Arbitrum shims with Polkad DA would suck in the same way as Optimism and Arbitrum, right?  Ok, if we can replicate the above tricks with more cores in a OpenEVM chains (where DOT revenue accrues to Polkadot Treasury, and not with EVM parachains with their own token), we can scrap Polkadot Rollups.   Can you kindly explain "cores with fewer approval checkers" to us and help us get beyond the above naive idea/ improve it  in a OpenEVM+CoreTime combined world?

So now that Polkadot 2.0 is virtualizing VMs themselves in work packages, I think for Polkadot EVM chains to compete in the broader Web3 marketplace (not in "we have better tech",  I mean like in terms of TVL, marketcap, TPS vanity metrics, etc.), utilizing the full power of cores on Frontier or whatever is better that is compatible with CoreTime is totally the thing to do.  Can we agree on this?

Whether an OpenEVM chain NEEDS to be a system chain or not a system chain can be decided by OpenGov, I don't think users really can see it, but I think the Circle+Tether+CEXes see the difference pretty clearly.  They clearly see a system chains like AssetHub with EVM powers totally different from a non-system chain with EVM powers, and I think for a key multiecosystem feature like USDC CCTP its a massive loss for Polkadot, and I don't see a coherent plan for this.   The hope might be, however, that with a lot of talented people in an OpenEVM collective an equivalent credibility would exist as if it were a system chain, and OpenEVM chain would be taken as seriously as a system chain by Circle+Tether+CEXes.  

Is this a Wish-for-Change type thing or an April Fool's joke?

**Comment by gonzaloetjo** [comment]
Everytime a core consumer / parachain / external agent develops a widely used tool, will we discuss if Polkadot should subsidize it into it's "common goood" space?  

Polkadot has a specific job, and bringing overhead costs (maintenance) and production costs (block-space) up should be carefully considered.

The question is if EVM makes the cut. Avalanche c-chain shows that it might.

**Comment by xermicus** [comment]
I think the scope should be reduced heavily to just concern the `contracts` pallet. The `contracts` pallet integrates well and doesn't need ETH compatiblity layers, it is heavily audited and used in production already by many parachains. Devs can write contracts using Rust, TypeScript and a Solidity dialect.

I don't understand what `EVM` and "rollups" have to do with making asset hub programmable in permission less way. I doubt it's needed and if so it can be added later, in an incremental fashion. I feel that by reducing the scope this RFC is a) more likely to succeed and b) much faster to be actually delivered.

**Comment by burdges** [comment]
I'd think https://forum.polkadot.network/t/contracts-update-solidity-on-polkavm/6949 supersedes this RFC, given polkavm contracts should definitely work.

**Comment by xermicus** [comment]
> I'd think https://forum.polkadot.network/t/contracts-update-solidity-on-polkavm/6949 supersedes this RFC, given polkavm contracts should definitely work.

Yes, and the target runtime likely won't diverge much from `contracts` as it is today. It'll take some time to get everything production ready though. In the meantime we could already test the waters on Kusama..

**Comment by sourabhniyogi** [comment]
> I think the scope should be reduced or broken up to just concern the `contracts` pallet. The `contracts` pallet integrates well and doesn't need ETH compatiblity layers, it is audited and used in production already by many parachains. Devs can write contracts using Rust, TypeScript and a Solidity dialect. 
>  I feel that by reducing the scope this RFC is a) more likely to succeed and b) much faster to be actually delivered.
Excellent.  I'll make the change based on 
https://forum.polkadot.network/t/contracts-update-solidity-on-polkavm/6949 
and resubmit.

**Pull request closed without merging**
