### PR TITLE
Introduce RFC mdBook web page

### PR DESCRIPTION
**Pull request by rzadp**
- Closes https://github.com/polkadot-fellows/RFCs/issues/53
- Preview available [here](https://paritytech.github.io/RFCs/).

Screenshot 2023-12-19 at 13 55 05

---

### What it does

- The workflow gathers the source markdown files of RFCs - approved ones, and proposed ones (from open PRs).
- The proposed RFCs are separated into new (<7 days since PR created) and stale (>30 days since PR updated).
- The RFCs are extended with a table of contents, and a link to the source.
- The RFCs are build into a web page using [mdBook](https://github.com/rust-lang/mdBook).
- The built web page gets pushed to `gh-pages` branch - to be published in Github Pages.
- The workflow is triggered on merge to `main`, and periodically once a day.

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]
lgtm, im sure there will be future iteration :)

**Review by bkchr — APPROVED** [review]

**Comment by ggwpez** [comment]
Is this the final URL https://paritytech.github.io/RFCs/ ?  
Then we should probably mention it in the README or even link it in the GitHub repo.

**Comment by rzadp** [comment]
The final URL is: https://polkadot-fellows.github.io/RFCs/

The paritytech one has served as a preview, before it was configured in polkadot-fellows.

**Comment by rzadp** [comment]
Hey @wirednkod, I didn't know about this dashboard 👍 

> merge the 2 and build the "cargo book" and then release it with the site

Do you have an idea on how we could do it in details?
I don't think the output of `mdBook` is gonna work properly inside a Vite SPA application, even forgetting about the design incosistency.

I see that the dashboard is fetching the PRs dynamically from Github. What if it fetched the RFC data from the mdBook Github branch instead? The branch is `gh-pages`, which gets published to Github Pages. I'm thinking I could add a json file with the data, so it would be a single fetch.

That way, the dashboard would operate on the same raw data, but present it with its own front-end design.
What do you think about this approach?

Unless we want to simply go with a link and keep only one site with full details - that seems reasonable too.

**Comment by wirednkod** [comment]
@rzadp mdBook is nothing more than generated `html` pages. If an iFrame (*yuk*) is added inside the fellowship site, then this would work. The point here is that the data on the mdbook are really detailed and nice - and I think, its better to add a link (to a new tab) towards the RFCs page that you creaed, instead of re-inventing the wheel. 

This way the `mdbook` would be part of the main page and still keep its own design and the work you have done.

I would like to suggest some changes to what you have if we agreed to go with the aforrementioned direction:
- remove introduction page
- Move `Newly Proposed` and `Proposed` categories above the `Approved` ones

I can add those as issues at [https://github.com/polkadot-fellows/RFCs/](https://github.com/polkadot-fellows/RFCs/)

**Comment by rzadp** [comment]
Sounds good, I agree with you.

> Move Newly Proposed and Proposed categories above the Approved ones

Makes total sense, no need to create an issue, I will do it right away.

> remove introduction page

It doesn't seem right for me, for a user who stumbles upon this link to not have any kind of description of what he's looking at. Are you sure about it? If the problem is that it's too short (a single sentence at the moment), we could add more to it.

**Comment by wirednkod** [comment]
@rzadp I have integrated now the RFC-book inside the dashboard (see sceenshot):
image

**Pull request merged**
